"""baseline

Revision ID: ead906254ac1
Revises: 
Create Date: 2026-09-15 18:24:32.577442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import server.models

# revision identifiers, used by Alembic.
revision: str = 'ead906254ac1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_user_id', sa.String(length=32), nullable=False),
    sa.Column('emp_code', sa.String(length=32), nullable=False),
    sa.Column('talenta_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'contract', 'notice', 'inactive', name='employeestatus', native_enum=False), nullable=False),
    sa.Column('shift_key', sa.String(length=16), nullable=False),
    sa.Column('roster_pattern', sa.String(length=16), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('created_at', server.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_device_user_id'), 'employees', ['device_user_id'], unique=True)
    op.create_index(op.f('ix_employees_emp_code'), 'employees', ['emp_code'], unique=True)
    op.create_index(op.f('ix_employees_talenta_id'), 'employees', ['talenta_id'], unique=True)
    op.create_table('export_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('draft', 'complete', 'blocked', name='exportstatus', native_enum=False), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('generated_at', server.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('gross_hours', sa.Float(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('daily_file', sa.String(length=256), nullable=True),
    sa.Column('pivot_file', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_runs_period'), 'export_runs', ['period'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day')
    )
    op.create_table('ingest_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('received_at', server.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('punches_submitted', sa.Integer(), nullable=False),
    sa.Column('punches_accepted', sa.Integer(), nullable=False),
    sa.Column('punches_duplicate', sa.Integer(), nullable=False),
    sa.Column('client_batch_ref', sa.String(length=64), nullable=True),
    sa.Column('earliest_punch', server.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('latest_punch', server.models.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_batches_agent_id'), 'ingest_batches', ['agent_id'], unique=False)
    op.create_table('day_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_key', sa.String(length=16), nullable=False),
    sa.Column('first_in', server.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_out', server.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('punch_count', sa.Integer(), nullable=False),
    sa.Column('worked_minutes', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('state', sa.Enum('open', 'resolved', 'final', name='daystate', native_enum=False), nullable=False),
    sa.Column('has_correction', sa.Boolean(), nullable=False),
    sa.Column('computed_at', server.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_dayrecord_identity')
    )
    op.create_index(op.f('ix_day_records_code'), 'day_records', ['code'], unique=False)
    op.create_index(op.f('ix_day_records_employee_id'), 'day_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_day_records_state'), 'day_records', ['state'], unique=False)
    op.create_index(op.f('ix_day_records_work_date'), 'day_records', ['work_date'], unique=False)
    op.create_table('punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('device_user_id', sa.String(length=32), nullable=False),
    sa.Column('punched_at', server.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('raw_punch_type', sa.Integer(), nullable=True),
    sa.Column('raw_status', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('device', 'manual_import', name='punchsource', native_enum=False), nullable=False),
    sa.Column('ingest_batch_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', server.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'device_user_id', 'punched_at', name='uq_punch_identity')
    )
    op.create_index(op.f('ix_punches_device_id'), 'punches', ['device_id'], unique=False)
    op.create_index(op.f('ix_punches_device_user_id'), 'punches', ['device_user_id'], unique=False)
    op.create_index(op.f('ix_punches_punched_at'), 'punches', ['punched_at'], unique=False)
    op.create_table('roster_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('working', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'day', name='uq_roster_override')
    )
    op.create_index(op.f('ix_roster_overrides_day'), 'roster_overrides', ['day'], unique=False)
    op.create_index(op.f('ix_roster_overrides_employee_id'), 'roster_overrides', ['employee_id'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_record_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.String(length=64), nullable=True),
    sa.Column('new_value', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', server.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['day_record_id'], ['day_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_day_record_id'), 'corrections', ['day_record_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_record_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('MP', 'SS', 'LONG', 'A', 'DUP', name='exceptionkind', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('open', 'resolved', name='exceptionstate', native_enum=False), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('opened_at', server.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', server.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolver', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['day_record_id'], ['day_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_record_id', 'kind', name='uq_exception_identity')
    )
    op.create_index(op.f('ix_exceptions_day_record_id'), 'exceptions', ['day_record_id'], unique=False)
    op.create_index(op.f('ix_exceptions_kind'), 'exceptions', ['kind'], unique=False)
    op.create_index(op.f('ix_exceptions_state'), 'exceptions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_state'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_kind'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_day_record_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_corrections_day_record_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_roster_overrides_employee_id'), table_name='roster_overrides')
    op.drop_index(op.f('ix_roster_overrides_day'), table_name='roster_overrides')
    op.drop_table('roster_overrides')
    op.drop_index(op.f('ix_punches_punched_at'), table_name='punches')
    op.drop_index(op.f('ix_punches_device_user_id'), table_name='punches')
    op.drop_index(op.f('ix_punches_device_id'), table_name='punches')
    op.drop_table('punches')
    op.drop_index(op.f('ix_day_records_work_date'), table_name='day_records')
    op.drop_index(op.f('ix_day_records_state'), table_name='day_records')
    op.drop_index(op.f('ix_day_records_employee_id'), table_name='day_records')
    op.drop_index(op.f('ix_day_records_code'), table_name='day_records')
    op.drop_table('day_records')
    op.drop_index(op.f('ix_ingest_batches_agent_id'), table_name='ingest_batches')
    op.drop_table('ingest_batches')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_export_runs_period'), table_name='export_runs')
    op.drop_table('export_runs')
    op.drop_index(op.f('ix_employees_talenta_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_emp_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_device_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
